# Generated by Django 4.2.19 on 2025-04-15 08:41

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('contact_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('inquiry_type', models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Adoption Inquiry', 'Adoption Inquiry'), ('Other', 'Other')], default='General Inquiry', max_length=200)),
                ('dog_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
