# Generated by Django 4.2.19 on 2025-04-10 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dateofbirth', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=20)),
                ('dogtype', models.CharField(choices=[('Labrador', 'Labrador'), ('Golden Retriever', 'Golden Retriever'), ('German Shepherd', 'German Shepherd'), ('Bulldog', 'Bulldog'), ('Poodle', 'Poodle'), ('Beagle', 'Beagle'), ('Rottweiler', 'Rottweiler'), ('Yorkshire Terrier', 'Yorkshire Terrier'), ('Boxer', 'Boxer'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('mircochip_no', models.CharField(blank=True, max_length=100)),
                ('desexed', models.BooleanField(default=False)),
                ('medical_history', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Dog',
                'verbose_name_plural': 'Dogs',
                'ordering': ['-created'],
            },
        ),
    ]
